### ISSUE TITLE
Errors for stack install 

### ISSUE THREAD

**Issue by chrissound** [yi-editor/yi#983] opened 2017-04-24 21:09 UTC
```
Downloading lts-8.12 build plan ...
Downloaded lts-8.12 build plan.
Populating index cache ...
Populated index cache.
[1 of 2] Compiling Main             ( /root/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /root/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /root/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 ...
data-default-class-0.1.2.0: download
data-default-class-0.1.2.0: configure
ansi-terminal-0.6.2.3: download
fingertree-0.1.1.0: download
generic-deriving-1.11.2: download
charsetdetect-ae-1.1.0.2: download
dlist-0.8.0.2: download
fmlist-0.9: download
executable-path-0.0.3.1: download
data-default-class-0.1.2.0: build
dlist-0.8.0.2: configure
dlist-0.8.0.2: build
ansi-terminal-0.6.2.3: configure
data-default-class-0.1.2.0: copy/register
ansi-terminal-0.6.2.3: build
fingertree-0.1.1.0: configure
data-default-instances-containers-0.0.1: download
fingertree-0.1.1.0: build
fmlist-0.9: configure
dlist-0.8.0.2: copy/register
fmlist-0.9: build
executable-path-0.0.3.1: configure
data-default-instances-dlist-0.0.1: download
executable-path-0.0.3.1: build
generic-deriving-1.11.2: configure
generic-deriving-1.11.2: build
charsetdetect-ae-1.1.0.2: configure
fmlist-0.9: copy/register
executable-path-0.0.3.1: copy/register
charsetdetect-ae-1.1.0.2: build
data-default-instances-containers-0.0.1: configure
ghc-paths-0.1.0.9: download
integer-logarithms-1.0.1: download
data-default-instances-containers-0.0.1: build
data-default-instances-dlist-0.0.1: configure
ansi-terminal-0.6.2.3: copy/register
data-default-instances-dlist-0.0.1: build
ghc-paths-0.1.0.9: configure
data-default-instances-containers-0.0.1: copy/register
ansi-wl-pprint-0.6.7.3: download
data-default-instances-dlist-0.0.1: copy/register
io-storage-0.3: download
fingertree-0.1.1.0: copy/register
microlens-0.4.8.0: download
mtl-2.2.1: download
ghc-paths-0.1.0.9: build
integer-logarithms-1.0.1: configure
integer-logarithms-1.0.1: build
ansi-wl-pprint-0.6.7.3: configure
ghc-paths-0.1.0.9: copy/register
ansi-wl-pprint-0.6.7.3: build
io-storage-0.3: configure
io-storage-0.3: build
microlens-0.4.8.0: configure
old-locale-1.0.0.7: download
integer-logarithms-1.0.1: copy/register
microlens-0.4.8.0: build
mtl-2.2.1: configure
io-storage-0.3: copy/register
oo-prototypes-0.1.0.0: download
ansi-wl-pprint-0.6.7.3: copy/register
mtl-2.2.1: build
old-locale-1.0.0.7: configure
parallel-3.2.1.1: download
pointedlist-0.6.1: download
old-locale-1.0.0.7: build
oo-prototypes-0.1.0.0: configure
charsetdetect-ae-1.1.0.2: copy/register
oo-prototypes-0.1.0.0: build
parallel-3.2.1.1: configure
microlens-0.4.8.0: copy/register
primitive-0.6.1.0: download
oo-prototypes-0.1.0.0: copy/register
parallel-3.2.1.1: build
pointedlist-0.6.1: configure
old-locale-1.0.0.7: copy/register
microlens-ghc-0.4.8.0: download
microlens-th-0.4.1.1: download
data-default-instances-old-locale-0.0.1: download
pointedlist-0.6.1: build
primitive-0.6.1.0: configure
primitive-0.6.1.0: build
microlens-ghc-0.4.8.0: configure
mtl-2.2.1: copy/register
parallel-3.2.1.1: copy/register
microlens-ghc-0.4.8.0: build
microlens-th-0.4.1.1: configure
random-1.1: download
pointedlist-0.6.1: copy/register
regex-base-0.93.2: download
microlens-th-0.4.1.1: build
data-default-instances-old-locale-0.0.1: configure
safe-0.3.14: download
data-default-instances-old-locale-0.0.1: build
random-1.1: configure
data-default-instances-old-locale-0.0.1: copy/register
random-1.1: build
regex-base-0.93.2: configure
microlens-ghc-0.4.8.0: copy/register
data-default-0.7.1.1: download
regex-base-0.93.2: build
safe-0.3.14: configure
semigroups-0.18.2: download
safe-0.3.14: build
data-default-0.7.1.1: configure
primitive-0.6.1.0: copy/register
data-default-0.7.1.1: build
semigroups-0.18.2: configure
split-0.2.3.1: download
data-default-0.7.1.1: copy/register
semigroups-0.18.2: build
split-0.2.3.1: configure
microlens-th-0.4.1.1: copy/register
stm-2.4.4.1: download
regex-base-0.93.2: copy/register
split-0.2.3.1: build
stm-2.4.4.1: configure
semigroups-0.18.2: copy/register
strict-0.3.2: download
terminfo-0.4.1.0: download
stm-2.4.4.1: build
strict-0.3.2: configure
text-1.2.2.1: download
safe-0.3.14: copy/register
strict-0.3.2: build
terminfo-0.4.1.0: configure
split-0.2.3.1: copy/register
transformers-compat-0.5.1.4: download
random-1.1: copy/register
unix-compat-0.4.3.1: download
tf-random-0.5: download
stm-2.4.4.1: copy/register
strict-0.3.2: copy/register
utf8-string-1.0.1.1: download
Hclip-3.0.0.4: download
terminfo-0.4.1.0: build
text-1.2.2.1: configure
text-1.2.2.1: build
transformers-compat-0.5.1.4: configure
transformers-compat-0.5.1.4: build
unix-compat-0.4.3.1: configure
generic-deriving-1.11.2: copy/register
unix-compat-0.4.3.1: build
tf-random-0.5: configure
transformers-compat-0.5.1.4: copy/register
tf-random-0.5: build
utf8-string-1.0.1.1: configure
vector-0.11.0.0: download
exceptions-0.8.3: download
utf8-string-1.0.1.1: build
Hclip-3.0.0.4: configure
terminfo-0.4.1.0: copy/register
Hclip-3.0.0.4: build
vector-0.11.0.0: configure
unix-compat-0.4.3.1: copy/register
vector-0.11.0.0: build
exceptions-0.8.3: configure
microlens-mtl-0.1.10.0: download
optparse-applicative-0.13.2.0: download
Hclip-3.0.0.4: copy/register
exceptions-0.8.3: build
microlens-mtl-0.1.10.0: configure
transformers-base-0.4.4: download
microlens-mtl-0.1.10.0: build
optparse-applicative-0.13.2.0: configure
tf-random-0.5: copy/register
optparse-applicative-0.13.2.0: build
transformers-base-0.4.4: configure
QuickCheck-2.9.2: download
transformers-base-0.4.4: build
QuickCheck-2.9.2: configure
utf8-string-1.0.1.1: copy/register
QuickCheck-2.9.2: build
exceptions-0.8.3: copy/register
word-trie-0.3.0: download
word-trie-0.3.0: configure
transformers-base-0.4.4: copy/register
microlens-mtl-0.1.10.0: copy/register
xdg-basedir-0.2.2: download
word-trie-0.3.0: build
xdg-basedir-0.2.2: configure
xdg-basedir-0.2.2: build
word-trie-0.3.0: copy/register
xdg-basedir-0.2.2: copy/register
dyre-0.8.12: download
dyre-0.8.12: configure
dyre-0.8.12: build
dyre-0.8.12: copy/register
optparse-applicative-0.13.2.0: copy/register
QuickCheck-2.9.2: copy/register
alex-3.2.1: download
alex-3.2.1: configure
alex-3.2.1: build
alex-3.2.1: copy/register
text-1.2.2.1: copy/register
hashable-1.2.6.0: download
parsec-3.1.11: download
glib-0.13.4.1: download
hashable-1.2.6.0: configure
cairo-0.13.3.1: download
text-icu-0.7.0.1: download
blaze-builder-0.4.0.2: download
hashable-1.2.6.0: build
parsec-3.1.11: configure
parsec-3.1.11: build
glib-0.13.4.1: configure
cairo-0.13.3.1: configure
text-icu-0.7.0.1: configure
blaze-builder-0.4.0.2: configure
blaze-builder-0.4.0.2: build
hashable-1.2.6.0: copy/register
blaze-builder-0.4.0.2: copy/register
parsec-3.1.11: copy/register
vector-0.11.0.0: copy/register

--  While building package text-icu-0.7.0.1 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/opt/ghc/8.0.2/bin/ghc --with-ghc-pkg=/opt/ghc/8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb --libdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/lib --bindir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/bin --datadir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/share --libexecdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/libexec --sysconfdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/etc --docdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/text-icu-0.7.0.1 --htmldir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/text-icu-0.7.0.1 --haddockdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/text-icu-0.7.0.1 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=deepseq=deepseq-1.4.2.0 --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/text-icu-0.7.0.1.log

    Configuring text-icu-0.7.0.1...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependencies on foreign
    libraries:
    * Missing C libraries: icuuc, icui18n, icudata
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.


--  While building package cairo-0.13.3.1 using:
      /opt/ghc/8.0.2/bin/ghc --make -odir /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb /tmp/stack7/cairo-0.13.3.1/Setup.hs /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/cairo-0.13.3.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/cairo-0.13.3.1/Setup.hs, /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    
    /tmp/stack7/cairo-0.13.3.1/Setup.hs:5:1: error:
        Failed to load interface for ‘Gtk2HsSetup’
        Use -v to see a list of the files searched for.


--  While building package glib-0.13.4.1 using:
      /opt/ghc/8.0.2/bin/ghc --make -odir /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb /tmp/stack7/glib-0.13.4.1/Setup.hs /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/glib-0.13.4.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/glib-0.13.4.1/Setup.hs, /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    
    /tmp/stack7/glib-0.13.4.1/Setup.hs:5:1: error:
        Failed to load interface for ‘Gtk2HsSetup’
        Use -v to see a list of the files searched for.
The command '/bin/sh -c stack install yi' returned a non-zero code: 1
```

**Comment by chrissound** [comment] 2017-04-24 21:18
`apt-get install -y libicu-dev` but I get stack at the next error:
```
--  While building package cairo-0.13.3.1 using:
      /opt/ghc/8.0.2/bin/ghc --make -odir /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb /tmp/stack7/cairo-0.13.3.1/Setup.hs /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/cairo-0.13.3.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/cairo-0.13.3.1/Setup.hs, /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    
    /tmp/stack7/cairo-0.13.3.1/Setup.hs:5:1: error:
        Failed to load interface for ‘Gtk2HsSetup’
        Use -v to see a list of the files searched for.


--  While building package glib-0.13.4.1 using:
      /opt/ghc/8.0.2/bin/ghc --make -odir /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb /tmp/stack7/glib-0.13.4.1/Setup.hs /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/glib-0.13.4.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/glib-0.13.4.1/Setup.hs, /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    
    /tmp/stack7/glib-0.13.4.1/Setup.hs:5:1: error:
        Failed to load interface for ‘Gtk2HsSetup’
        Use -v to see a list of the files searched for.
```

**Comment by Fuuzetsu** [comment] 2017-04-25 09:31
you can look in shell.nix to find a list of non-Haskell dependencies you need to install; or if you have nix just run `stack --nix install` and everything should Just Work.

**Comment by noughtmare** [comment] 2017-04-25 11:10
Running `stack install gtk2hs-buildtools` should fix this error.

**Comment by chrissound** [comment] 2017-04-30 21:48
Does anyone know which package is required for `cairo` on Ubuntu?
```
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/cairo-0.13.3.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/cairo-0.13.3.1/Setup.hs, /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /tmp/stack7/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup ...
    Configuring cairo-0.13.3.1...
    setup: The pkg-config package 'cairo' version >=1.2.0 is required but it could
    not be found.


--  While building package glib-0.13.4.1 using:
      /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/opt/ghc/8.0.2/bin/ghc --with-ghc-pkg=/opt/ghc/8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/pkgdb --libdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/lib --bindir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/bin --datadir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/share --libexecdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/libexec --sysconfdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/etc --docdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/glib-0.13.4.1 --htmldir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/glib-0.13.4.1 --haddockdir=/root/.stack/snapshots/x86_64-linux/lts-8.12/8.0.2/doc/glib-0.13.4.1 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=containers=containers-0.5.7.1 --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5
    Process exited with code: ExitFailure 1
    Logs have been written to: /.stack-work/logs/glib-0.13.4.1.log

    [1 of 2] Compiling Main             ( /tmp/stack7/glib-0.13.4.1/Setup.hs, /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /tmp/stack7/glib-0.13.4.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup ...
    Configuring glib-0.13.4.1...
    setup: The pkg-config package 'glib-2.0' is required but it could not be
    found.
```

`apt-get install -y cairo` gives me a `Unable to locate package cairo` which is weird as it seems to be listed here: https://launchpad.net/ubuntu/+source/cairo

**Comment by noughtmare** [comment] 2017-05-01 12:34
I think the problem is that (the haskell packages) `cairo` and `glib` fail to build because `gtk2hs-buildtools` (haskell package) is not installed. So running `stack install gtk2hs-buildtools` and then rebuilding yi should work. 

So there were two errors as far as I can tell: the `libicu-dev` (ubuntu) package was not installed (which you now fixed) and the `gtk2hs-builtools` (haskell) package is not installed.

My previous comment was probably a bit confusing as I had not read the entire post. I have now updated it to specify which error I meant.

**Comment by chrissound** [comment] 2017-05-01 13:28
That is after I've run that command. I'm doing this with docker and the dockerfile looks like this:
```
FROM haskell:8.0.2
RUN cabal update && stack update
RUN apt-get update
RUN apt-get install -y libicu-dev 
RUN stack install gtk2hs-buildtools
ADD stack.yaml .
RUN apt-get install -y pkg-config
RUN apt-get update
RUN apt-get install -y cairo
ADD stack.yaml .
RUN stack install yi
ENTRYPOINT yi
```

**Comment by noughtmare** [comment] 2017-05-01 14:44
Ah, then you probably indeed need to install the ubuntu packages cairo and glib. 

I don't know a lot about ubuntu, but (after some googeling) I found the `libcairo2-dev` and `libglib2.0-dev` (ubuntu) packages. Those are probably the packages that you need.

**Comment by noughtmare** [comment] 2017-05-22 19:03
@chrissound Did you succeed?

**Comment by ethercrow** [comment] 2017-06-17 15:43
@chrissound Closing because of inactivity, please feel free to reopen.

**Closed by ethercrow** 2017-06-17 15:43 UTC

**Comment by chrissound** [comment] 2017-08-15 08:26
I've just pulled the stack.yaml of the repo, and updated the Dockefile to:
```
FROM haskell:8.0.2
RUN cabal update && stack update
RUN apt-get update
RUN apt-get install -y libicu-dev 
RUN stack install gtk2hs-buildtools
RUN apt-get install -y pkg-config
RUN apt-get install -y libcairo2-dev libglib2.0-dev
ADD stack.yaml .
RUN stack install yi
ENTRYPOINT yi
```
`stack install yi` fails with:
Downloading lts-8.18 build plan ...
Downloaded lts-8.18 build plan.
/yi-core: canonicalizePath: does not exist (No such file or directory)

**Comment by noughtmare** [comment] 2017-08-15 10:48
@chrissound In the stack.yaml it is indicated that subpackages (like `yi-core` and `yi-language-haskell`) exist, the error you get is that stack can't find those subpackages. To fix this error you would have to add the complete source code of Yi, but I don't think that is what you want. You could also remove all the items under the `packages:` field in the `stack.yaml` file, but the only thing that will be left is basically the resolver version, which you could indicate by adding the `--resolver lts-8.18` to the `stack install yi` command.

Why did you add the `stack.yaml`, what problem do you think that solves?
