### ISSUE TITLE
Yi seems to modify copied text in new and old position

### ISSUE THREAD

**Issue by codygman** [yi-editor/yi#1022] opened 2017-08-05 05:28 UTC
This is a bit difficult to explain, so here's a video:
https://youtu.be/aYmQ0yammtI

It's almost if I have multiple cursors on, but I don't think Yi has those. To try and record the steps I took:

1. I built yi/example-configs/yi-vim-vty-static as of e0ac8207f5487865f1a4057f3ef5b036db0a6c54
2. I opened yi/example-configs/yi-vim-vty-static/Main.hs with newly built `yi-vim-vty-static`
3. I went to the bottom of the file and started a comment with:
```
{-

-}
```
4. I pasted this code in the comment
```
import Yi
import Yi.Keymap.Vim (keymapSet, mkKeymapSet, defVimConfig, vimExCommandParsers)
import qualified Yi.Mode.Haskell as Haskell
import Yi.Style
import Yi.Style.Library

-- For Ex command
import qualified Text.ParserCombinators.Parsec as P
import Yi.Keymap
import Yi.Keymap.Vim.Ex.Types
import qualified Yi.Keymap.Vim.Ex.Commands.Common as Common

defaultVimUiTheme :: Theme
defaultVimUiTheme = defaultTheme  `override` \super self -> super {
        selectedStyle = modelineFocusStyle self
 }

myConfigUI :: UIConfig
myConfigUI = (configUI defaultVimConfig)  {
        configFontSize = Just 10,
        configTheme = defaultVimUiTheme,
        configWindowFill = '~'
 }

main :: IO ()
main = yi $ defaultVimConfig {
    configUI = myConfigUI,
    defaultKm = mkKeymapSet $ defVimConfig `override` \ super self -> super
            { vimExCommandParsers = myExCmdParsers ++ vimExCommandParsers super }
 }

-- A custom macro
helloWorld :: YiM ()
helloWorld = withBuffer $ insertN "Hello, world!"

-- helloWorld Ex Command
parse :: String -> Maybe ExCommand
parse = Common.parse $ do
    P.string "helloWorld"
    return $! Common.impureExCommand {
        cmdAction = YiA $ helloWorld
      , cmdShow = "helloWorld"
      }

myExCmdParsers = [parse]
```
5. I copied all lines from --- A custom macro` to the end of the file.
6. I pasted it right below defaultConfig
7. It pasted with extra indentation, so I started deleting it and noticed that whitespace was getting deleted where my cursor was *and* where I copied the text from.

**Comment by ethercrow** [comment] 2017-08-05 08:11
Could you try the same sequence in a file named `foo.txt` or something like that? I suspect this bug is caused by haskell mode being too clever.

**Comment by ethercrow** [comment] 2017-08-05 08:13
Just in case someone finds it helpful, `:set paste` protects you from such breakage of indentation when pasting.

**Comment by noughtmare** [comment] 2017-08-05 09:48
It has nothing to do with copying. It is a bug in the indentation code.
Another example:
```haskell
       this
       is
       an
       indented
       block

{-
this is some
   text
   with indentation
-}
```
Deleting any space before the word this on the second line will not only move the indented block, but also the indented part of the text with indentation inside the comment.

**Comment by noughtmare** [comment] 2017-08-05 09:54
Oh, wait. The block below is only moved if one of the first three spaces is removed. If you just backspace starting with the cursor on the 't' of "this", then nothing happens to the lower block for the first four backspaces.

**Comment by noughtmare** [comment] 2018-03-01 11:56
I just found out this is actually a duplicate of #173

**Comment by noughtmare** [comment] 2018-03-01 12:02
This has been "solved" by https://github.com/yi-editor/yi/commit/3f6df013d500fc982e38ecc5a9993a7730b4ac2d.

**Closed by noughtmare** 2018-03-01 12:02 UTC
Labels: bug, mode-haskell
