### ISSUE TITLE
yi-language and yi-misc-modes 0.13.4 build failure with alex 3.2.0 and 3.2.1

### ISSUE THREAD

**Issue by snoyberg** [yi-editor/yi#922] opened 2016-10-11 05:43 UTC
```
[10 of 10] Compiling Yi.Lexer.Compilation ( dist/build/Yi/Lexer/Compilation.hs, dist/build/Yi/Lexer/Compilation.o )

src/Yi/Lexer/common.hsinc:24:34-48: error:
    • Couldn't match expected type ‘[(Yi.Buffer.Basic.Point, Char)]
                                    -> HlState -> (t, t1)’
                  with actual type ‘Int’
    • The function ‘act’ is applied to two arguments,
      but its type ‘Int’ has none
      In the expression: act chunk state
      In a pattern binding: (state', tokValue) = act chunk state
    • Relevant bindings include
        state' :: t (bound at src/Yi/Lexer/common.hsinc:24:14)
        tokValue :: t1 (bound at src/Yi/Lexer/common.hsinc:24:22)
```

**Comment by ethercrow** [comment] 2016-10-11 05:52
Thank you for reporting, Michael. I don't see this in our travis build. Usually errors in that file come up when there are some breaking changes in alex. What alex version do you have there?

**Comment by snoyberg** [comment] 2016-10-11 05:56
Ah, that would appear to be the source. Looks like alex just upgraded to 3.2.0. I can put in a temporary upper bound.

**Comment by snoyberg** [comment] 2016-10-11 06:01
Sorry, my mistake, we're still using 3.1.7.

**Comment by snoyberg** [comment] 2016-10-11 06:12
Alright, sorry for the confusion: it _was_ using 3.2.0. I'm fixing a bug in the build scripts that let old executables accidentally persist.

**Comment by juhp** [comment] 2016-10-12 02:28
(Thanks I reported this too at yi-editor/yi-language#12)

**Comment by ethercrow** [comment] 2016-10-23 19:17
Until it's fixed I've released 0.13.3 with an upper bound `alex < 3.2.0`

**Comment by ethercrow** [comment] 2016-10-23 19:18
@snoyberg is that enough to bring back yi packages into stackage nightly?

**Comment by juhp** [comment] 2016-10-24 02:09
We currently have alex-3.2.1 in Stackage Nightly so it won't help.

**Comment by ethercrow** [comment] 2016-12-03 17:40
It turns out alex-3.2.1 has a fix for this breakage of 3.2.0, so I've released yi 0.13.4 that blacklists alex-3.2.0 and made a PR to stackage here https://github.com/fpco/stackage/pull/2109

**Comment by juhp** [comment] 2016-12-03 23:31
Still looks broken to me yi-editor/yi#944 with alex-3.2.1.

**Comment by ethercrow** [comment] 2016-12-04 06:32
Yeah, I've probably mixed something up locally so that it was building normally.

**Comment by ethercrow** [comment] 2016-12-06 10:55
I've asked for help in alex repo https://github.com/simonmar/alex/issues/102

**Comment by realcomplex** [comment] 2016-12-07 21:46
I wanted to try out Yi, but "cabal install yi" is failing due this issue. Any workaround for now, or should I just wait it out?

**Comment by ethercrow** [comment] 2016-12-07 22:01
@realcomplex I'm working on it

**Comment by realcomplex** [comment] 2016-12-07 22:02
Alright, thank you in advance for your work!

**Comment by noughtmare** [comment] 2016-12-07 22:31
@realcomplex You should be able to install yi with stack using the stackage lts 7.12 (to do this you probably only need to install stack and then run `stack install yi`).

**Comment by juhp** [comment] 2016-12-08 01:17
@realcomplex or cabal-install with a older version of alex installed?
I have alex-3.1.7 here on my F25 machine and `cabal install yi` succeeded for me, but yes as @noughtmare said `stack --resolver lts-7 yi` should also work.

**Comment by realcomplex** [comment] 2016-12-08 01:47
I got it to work with stack, thanks for the help!

**Comment by ethercrow** [comment] 2016-12-09 10:55
@juhp can you confirm if the issue is fixed in master or must I make a hackage release first?

**Comment by juhp** [comment] 2016-12-10 01:03
Thanks
I tried running `stack --resolver nightly install` (and `stack install`) but i couldn't get cairo to build: I think it is a known issue that stack doesn't handle custom Setup well iirc.
Also I couldn't manage to persuade stack to disable pango... maybe my stack fu is not up to it...

Did it work for you?  I think i would be best if you could release to Hackage: that will allow building/testing in Stackage.

**Comment by ethercrow** [comment] 2016-12-10 10:04
@juhp Unfortunately, I wasn't able to install gtk-related stuff either.

New PR to stackage: https://github.com/fpco/stackage/pull/2131

**Comment by juhp** [comment] 2016-12-10 12:09
Thank you

**Closed** 2016-12-15 20:25 UTC
Labels: High priority
