### ISSUE TITLE
Fix GHC warnings

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#808] opened 2016-06-27 14:42 UTC
When building Yi with stack it generates these warnings:
~~[yi-0.12.6.log](https://gist.github.com/noughtmare/565d2f963f89c5840dc21c67090de241)~~ (A lot of these are fixed now, see comments down below for unfixed warnings)

**Comment by ethercrow** [comment] 2016-06-27 15:05
If a warning is not caused by a compatibility reason, it should be fixed. Currently we try to support 7.8, 7.10 and 8.0, but it might be already the right time to drop 7.8.

**Comment by noughtmare** [comment] 2016-06-28 11:25
I don't know how to fix:
```
src/library/Yi/Syntax/JavaScript.hs:120:10-25: Warning:
    No explicit implementation for
      ‘uniplate’ and ‘emptyNode’
In the instance declaration for ‘IsTree Statement’
```

**Comment by noughtmare** [comment] 2016-06-28 20:52
I also don't know how to fix:
```
src/library/Yi/Main.hs:15:1-26: Warning:                                                                  
    Module ‘Control.Monad.Error’ is deprecated:                                                           
      Use Control.Monad.Except instead                                                                    
                                                                                                          
src/library/Yi/Main.hs:43:10-14: Warning:                                                                 
    In the use of type constructor or class ‘Error’                                                       
    (imported from Control.Monad.Error, but defined in transformers-0.4.2.0:Control.Monad.Trans.Error):   
    Deprecated: "Use Control.Monad.Trans.Except instead"                                                  
                                                                                                          
src/library/Yi/Main.hs:43:10-14: Warning:                                                                 
    In the use of type constructor or class ‘Error’                                                       
    (imported from Control.Monad.Error, but defined in transformers-0.4.2.0:Control.Monad.Trans.Error):   
    Deprecated: "Use Control.Monad.Trans.Except instead"
```

**Closed** 2016-07-10 16:45 UTC
